### ISSUE TITLE
unpack & unpackDir options ignored

### ISSUE THREAD

**Issue by kanekotic** [electron/asar#101]
I am using asar to pack an application served through express. In my case I am using gulp to achive this packing
```js
gulp.task('generate-asar', function (callback) {
    var src = 'dist';
    var dest = 'dist/app.asar';
    var opts = {
        unpack: '{' + [
        '*.asar',
        'server.js'
        ].join(',') + '}'
    };

    asar.createPackageWithOptions(src, dest, opts, callback);
});
```
after running the gulp task
```
kanekotic@kanekotic-Laptop:/media/shared/workspace/app$ ./node_modules/asar/bin/asar l ./dist/app.asar
/blob.css
/blob.js
/index.html
/server.js
```
On second run the asar file will be also packed...
 I have tried using the option unpackDir, and also tried to use it from command line (```./node_modules/asar/bin/asar pack dist app.asar --unpack "{server.js,app.asar}"```) the behaviour is the same. Any idea on what is happening or if I am doing something fundamentally wrong
Environment:
    - OS: Ubuntu 16.04
    - node: 4.7

**Comment by kevinsawicki** [comment]
The `--unpack` option causes a `app.asar.unpacked` folder to be created with the specified contents their instead of inside the `app.asar` file.

It seems like instead you want to just ignore `app.asar` and package everything in the `dist/` folder except it, is that accurate?

**Comment by kanekotic** [comment]
yes exactly that is accurate...
If not there is a really nasty behaviour of recursively try to add the `asar`. As asar already exist when listed it try to recursively add itself over and over again, till it ends up in an exception due the file size gets to the maximum allowed by the OS. 
In my case when faced with this at that point I tried `umpack-dir` and also `unpack`. and both gave me the same behaviour. As a workaround now in my own builds i am unlinking/removing the file before generating the asar again. But itself I reported it because i dont think `umpack-dir` and also `unpack` are working as described in the documentation.

**Comment by kevinsawicki** [comment]
>  As a workaround now in my own builds i am unlinking/removing the file before generating the asar again.

Yes, this is a better approach since the asar API does not have an ignore option. Unpacking is completely different than ignoring, unpacking should only be used for specifying files/folders that cannot exist inside a `.asar` file like `.node` files. See http://electron.atom.io/docs/tutorial/application-packaging/#limitations-of-the-node-api for more details.

You can also use `electron-packager` which has support for ignoring files that should not be included in the `.asar` file: https://github.com/electron-userland/electron-packager#usage
