### ISSUE TITLE
What is the plan for `mksnapshot`?

### ISSUE THREAD

**Issue by pzrq** [electron/asar#102]
Does anyone know what the plan is for `mksnapshot`?

It looks like `mksnapshot` is still used, e.g. it is listed in package.json:
https://github.com/electron/asar/search?utf8=%E2%9C%93&q=mksnapshot

However it seems to have been moved into [electron-archive](https://github.com/electron-archive), which states `Electron repositories no longer maintained`:
https://github.com/electron-archive/node-mksnapshot

Was it incorrectly moved to [electron-archive](https://github.com/electron-archive) or are there plans to replace `mksnapshot` with something else?

**Comment by kevinsawicki** [comment]
@pzrq New `mksnapshot` binaries will still be released on each new minor version of Electron available to download as assets from https://github.com/electron/electron/releases/tag/v1.4.0

The `node-mksnapshot` repository was a small wrapper around these libraries that wasn't actively maintained and so it was moved to the archive org.

The plan is to release a new wrapper that is more in the style of https://github.com/electron/chromedriver which allows you to run `npm install electron-mksnapshot` to install the binary but it will just be a simple CLI wrapper around the downloaded tool.

**Comment by kevinsawicki** [comment]
@pzrq I set up a new repository at https://github.com/electron/mksnapshot for this new version and published a 1.4.0 version.

You can run `npm install electron-mksnapshot` to install, please open new issues over on that repository for any issues, features, etc.
