### ISSUE TITLE
File listing of a folder inside the asar archive with readdir/readdirSync, doesn't work

### ISSUE THREAD

**Issue by nikolayanchev** [electron/asar#103]
When trying to get the file list of a directory inside the asar file, the file list of the top directory is returned.for example in a asar packed electron app, when you do fs.readdirsync on a path inside node_modules it returns only the listing for the top directory of the asar package.
Is this a bug, or is it supposed to work like that?

**Comment by ivanseidel** [comment]
Same problem here. It used to work, but it isn't anymore.

**Comment by SimoneTosato** [comment]
:+1: same here

**Comment by booleangate** [comment]
Sample code

```
const dirname = path.dirname(filePath) + path.sep;
const files = fs.readdirSync(dirname);

console.log(filePath);
console.log(`  dirname = ${dirname}`);
console.log(`  files = ${files}`);
```

Output
```
/Users/johnsonj/dev/my-project/native/dist/my-project-darwin-x64/my-project.app/Contents/Resources/app.asar/src/widgets/native/widgets/renderers/base.js
  dirname = /Users/johnsonj/dev/my-project/native/dist/my-project-darwin-x64/my-project.app/Contents/Resources/app.asar/src/widgets/native/widgets/renderers/
  readdir = .eslintrc,.gitignore,assets,bin,config,node_modules,package.json,src
```

It's my understanding that Electron is monkey patching node's `fs` to make asar packaging transparent to applications.  Is `fs.readdir`/`fs.readdirSync` just not patched?

**Comment by booleangate** [comment]
After further testing, if I don't include  `path.sep` at the end of the path passed to `fs.readdir` it works as expected.  I would still say that is a bug though.

**Comment by booleangate** [comment]
After further testing, if I don't include  `path.sep` at the end of the path passed to `fs.readdir` it works as expected.  I would still say that is a bug though.

**Comment by cookiejest** [comment]
im getting this problem also :/

**Comment by tjfryan** [comment]
Ran into this as well.  @booleangate's solution of removing the path separator makes it appear to work.

**Comment by pierbettassa** [comment]
> 
> 
> Ran into this as well. @booleangate's solution of removing the path separator makes it appear to work.

Same here!

**Comment by darron1217** [comment]
It's still not working in electron 10.1.1

my code
```
const dir = 'C:\Users\darron\Desktop\electron-strapi\dist\win-unpacked\resources\app.asar\config';
const fs = require('fs');
fs.readdirSync(dir, { withFileTypes: true }); // results []
```

**Comment by malept** [comment]
This is an issue with Electron itself rather than the asar module. Please file a bug in that repository's issue tracker with a minimal example based on the `electron/electron-quick-start` git repository.
