### ISSUE TITLE
Intermittent truncated file content

### ISSUE THREAD

**Issue by njentit** [electron/asar#106]
Listening on transforn end [https://github.com/electron/asar/blob/master/lib/filesystem.js#L84](url) will producing intermittent output as writer stream maybe not yet closed even when transfrom has reached end state.  I suggest change it into listening on writer close:

`return out.on('close', function() {`

For my case it producing consistent output.

**Comment by pauliusuza** [comment]
I have a use case with electron-builder since version v14.2.0 (it's working in v14.1.1).


```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /repo/node_modules/electron-builder/src/util/readPackageJson.ts:76:46
    at Generator.throw (<anonymous>)
    at Generator.tryCatcher (/repo/node_modules/bluebird/js/release/util.js:16:23)
```

**Comment by develar** [comment]
Electron-builder will use own old forked version, sorry for inconvenience, I will check what's wrong with latest asar.

**Comment by malept** [comment]
It's unclear whether this is still a bug in the current version of `asar`. If it is, please comment with a way to reliably reproduce this (so we can figure out how to write a regression test in the testsuite) and we can reopen this issue.
