### ISSUE TITLE
Project abandon

### ISSUE THREAD

**Issue by kanekotic** [electron/asar#107]
Is this project being abandon? I cannot see any participation from electron team since more than 3 months

**Comment by kevinsawicki** [comment]
> Is this project being abandon?

Nope, it isn't abandoned, we did a release last month.

**Comment by kanekotic** [comment]
@kevinsawicki great to hear because i haven't seen any of the technical issues posted being answered . I have tried excluding some files like posted in issue #101 exactly 2 months ago, and still on the air. that is why I open this question.
Can we have access to the latest release notes? or extra information to know if the issues we faced are solve and close our own other issues?.

**Comment by kevinsawicki** [comment]
> Can we have access to the latest release notes?

You can find them at https://github.com/electron/asar/blob/master/CHANGELOG.md
