### ISSUE TITLE
--ordering not working on Windows (forward vs. backward slashes)

### ISSUE THREAD

**Issue by romaincointepas** [electron/asar#108]
[`glob`](https://github.com/isaacs/node-glob) always returns results with forward-slashes (`/`), even on Windows (see this [issue](https://github.com/isaacs/node-glob/issues/173)).

However, when parsing the Windows-generated hint file passed to `--ordering`, all paths have backward-slashes (`\`), meaning there will never be any matches, always resulting in 0% coverage.

cc @bengotow, original PR #52

**Comment by romaincointepas** [comment]
A temporary fix could be to do something like this:

```javascript
if (path.sep === '\\') {
  str = str.replace(/\\/g, '/');
}
ordering.push(str);

```
at https://github.com/electron/asar/blob/master/lib/asar.js#L78

**Comment by bruceauyeung** [comment]
Does this problem still exist on Windows platform ?

**Comment by MarshallOfSound** [comment]
Closing this old issue as it is likely fixed by now, if not please raise a new issue.
