### ISSUE TITLE
[SOLVED] Different behaviour packing command line and npm

### ISSUE THREAD

**Issue by xanisu** [electron/asar#109]
That runs ok on windows 7:
`c:/asar pack app app.asar`
`c:/asar extract app.asar app`

But if I run this process through `npm`, or `gulp-asar`, it fails. The asar file is created, but it fails on extract, it has slightly different size compared to when I create it directly through console.

**Why?**

 - npm: v3.10.6  
 - node: v4.5.0
 - asar: v0.13.0
 - electron: v1.4.3

I've already opened and answer in stackoverflow cause, I'm stucked with this problem.

http://stackoverflow.com/questions/42267968/different-behaviour-between-npm-run-command-and-windows-console

**Comment by xanisu** [comment]
just solved it, seems to be a conflict in any other package in my project, cause testing it alone worked so:

-Removed all node_modules in my project, and done "npm install" again.

Worked like a charm after the install.

**Comment by kevinsawicki** [comment]
> Worked like a charm after the install.

Thanks for the update, closing this out.
