### ISSUE TITLE
7-Zip plugin

### ISSUE THREAD

**Issue by Daniel15** [electron/asar#110]
It would be good to have a 7-Zip plugin for ASAR, in order to allow archives to be browsed and extracted using 7-Zip 😃

**Comment by Gnafu** [comment]
I agree, I use 7-zip a lot to check whatever package my pipeline is generating (zip, war, apk, whatever)

**Comment by pombredanne** [comment]
Should this be reported to 7zip instead?

**Comment by Daniel15** [comment]
Maybe, although I'm pretty sure it's possible to make third party plugins
for 7zip.

Sent from my phone.

On Jun 1, 2017 2:01 AM, "Philippe Ombredanne" <notifications@github.com>
wrote:

Should this be reported to 7zip instead?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/electron/asar/issues/110#issuecomment-305234070>, or mute
the thread

**Comment by DenisAnisimov** [comment]
I created asar plugin for 7z:


![asar](https://user-images.githubusercontent.com/23529525/33768292-8077d46e-dc36-11e7-8dd9-de1abea6117d.png)

Plugin home page: http://www.tc4shell.com/en/7zip/asar/
I hope it will be useful to someone.

**Comment by pombredanne** [comment]
@DenisAnisimov does it work on the command line too and elsewhere than Windows ? And where could I find the sources? Have you considered contributing this to Igor @ 7zip?

**Comment by DenisAnisimov** [comment]
@pombredanne 1) I did not tested but it should work with 7z in command line mode. 2) Asar7z is plugin for 7Zip so it works only on Windows. 3) This is not open source project. 4) Igor never accept any external code.

**Comment by pombredanne** [comment]
@DenisAnisimov Thanks the p7zip port works nicely on Linux...
That said, your fine code is useless to me if not open and windows only.

**Comment by carlzoo** [comment]
The download link is offline for me at the moment.

**Comment by aardio** [comment]
https://github.com/aardio/WinAsar
Portable and lightweight GUI utility to pack and extract asar files, Only 551 KB!
![image](https://user-images.githubusercontent.com/14340891/116769163-c13b2200-aa6c-11eb-830f-c909909b91ed.png)

**Comment by woctezuma** [comment]
I ended up here thanks to [StackOverflow](https://stackoverflow.com/a/53030778/376454).

`Asar.64.dll` does not seem to work for my use case. Since the plugin was last released in version 1.2 on 2020-03-05, I have tried different 64-bit versions of 7-Zip:
- 21.07 (2021-12-26),
- 19.00 (2019-02-21),
- 16.04 (2016-10-04).
I always get an "unspecified error".

I don't want to try WinAsar, posted just above, because VirusTotal sends warnings about it.

**Comment by aardio** [comment]
@woctezuma 
That's a false positive.
WinAsar is an open source software and doesn't contain a virus.
![image](https://user-images.githubusercontent.com/14340891/161611393-89f608ab-4b7f-4295-8a80-20ae90aa94f5.png)

**Comment by timea-techgirl** [comment]
> I created asar plugin for 7z:
> 
> Plugin home page: http://www.tc4shell.com/en/7zip/asar/ I hope it will be useful to someone.

I love this plugin, it's very useful to me but it's not working for latest asar files.

**Comment by DenisAnisimov** [comment]
> it's not working for latest asar files.

Can you provide a sample of such asar file?

**Comment by timea-techgirl** [comment]
> > it's not working for latest asar files.
> 
> Can you provide a sample of such asar file?

Here it is:
https://drive.google.com/file/d/1xePszAOhmPrO4x7VxBN_zqeGa_hFIL_f/view?usp=sharing

**Comment by DenisAnisimov** [comment]
> Here it is:

Fixed.

**Comment by malept** [comment]
Can you please use a different forum to provide support for your plugin? This issue tracker is meant for this Node.js implementation.

The Electron maintainers are not going to build a 7-zip plugin, so I'm closing this.

**Comment by mcjambi** [comment]
it is not working, in my case!

**Comment by modz2014** [comment]
there is no source code for those 7zip plugins at all would be nice if they were open source

**Comment by DaPa** [comment]
Asar.64.dll v1.4 (28 Nov 2022, latest from https://www.tc4shell.com/en/7zip/asar/) works perfectly with 7-Zip 23.01 (x64): just copy Asar.64.dll into the "7-zip\Formats" subfolder:
![7z](https://github.com/electron/asar/assets/4947697/6894c0aa-97d4-4e71-8bd5-cd29ef878e80)

As well it works with the Total7zip pluging of Total Commander (just copy the same dll into totalcmd\plugins\wcx\Total7zip\64\Codecs\):
![tc](https://github.com/electron/asar/assets/4947697/4b0bbb9a-890f-42ff-a333-954bfd3f3fd0)

And btw this Total7zip plugin integrates with BeyondCompare too:
![bc1](https://github.com/electron/asar/assets/4947697/523c20c9-7f63-4b0f-991c-b2b725485845)
![bc2](https://github.com/electron/asar/assets/4947697/29901db3-ce4a-48d4-8b8e-0585a8157c18)

**Comment by rpodric** [comment]
@DaPa I use that DLL version with 7Zip too, but recently I started to see a couple "ERROR: CRC Failed" results consistently (for an asar from one particular program that is updated periodically), whether I'm using the GUI or 7z.exe. I'm not sure what's going on yet, as the two DLLs in question showing the CRC failures don't appear to be corrupt. A slew of other files are also extracted but don't show the problem, so it's hard to understand how it could be false. I guess I'll try to find some other way to extract it for a point of comparison.

**Comment by DenisAnisimov** [comment]
@rpodric Judging by the description, the SHA value specified in the asar file does not match the actual SHA value of the data. It’s better to write to the plugin developer (that is, me) by email and send a sample of the problem asar file.

**Comment by rpodric** [comment]
@DenisAnisimov That would be great. It does feel more like something messed up in the asar (though if it is they've done it more than once) than anything to do with extraction, so what you say makes sense. I haven't found an alternative way to extract yet, so your looking at it would help.

I assume the address showing on the contact form is the one to use?

**Comment by DenisAnisimov** [comment]
@rpodric 

> I assume the address showing on the contact form is the one to use?

Yes.

**Comment by s2candy2013** [comment]
> I created asar plugin for 7z:
> 
> ![asar](https://user-images.githubusercontent.com/23529525/33768292-8077d46e-dc36-11e7-8dd9-de1abea6117d.png)
> 
> Plugin home page: http://www.tc4shell.com/en/7zip/asar/ I hope it will be useful to someone.
it doesnt work for me, can u  check encrypt method then update your asar plugin in 7zip, link below
https://drive.google.com/file/d/1SLSR0hDeGNBQwvVdqdoQ_73B6tHaWPPu/view?usp=sharing

**Comment by iG8R** [comment]
@DaPa 
Could you please tell how you integrated Total7zip into BeyondCompare, specifically, did you add the masks manually?
Have you been able to compare files inside asar archives not only by CRC but also binary-wise?
Because I keep getting an error - Data is bad.
![image](https://github.com/electron/asar/assets/11407417/aacf4018-d6fa-41f6-9035-2fbfcb610f00)

**Comment by debugginglife** [comment]
@DenisAnisimov: Can you please have the MD5 plugin for 7Zip as opensource, assuming you are the one who is the owner of tc4shell.com

**Comment by modz2014** [comment]
they wont release the source code because it contains malware and all that stuff @debugginglife

**Comment by modz2014** [comment]
@debugginglife @Daniel15 @DenisAnisimov 
I wouldn't recommend using any of the Total7zip plugins, as they access the registry unnecessarily. If it's just a 7zip plugin, there shouldn't be any need for that. I’ve started creating my own plugin, which will be open source. The only reason they don’t share their source code is that it likely contains malware and other questionable elements.

![Image](https://github.com/user-attachments/assets/2ea837c2-1cd4-44f4-8f5b-05d39c60f621)

**Comment by debugginglife** [comment]
> [@debugginglife](https://github.com/debugginglife) [@Daniel15](https://github.com/Daniel15) [@DenisAnisimov](https://github.com/DenisAnisimov) I wouldn't recommend using any of the Total7zip plugins, as they access the registry unnecessarily. If it's just a 7zip plugin, there shouldn't be any need for that. I’ve started creating my own plugin, which will be open source. The only reason they don’t share their source code is that it likely contains malware and other questionable elements.
> 
> ![Image](https://github.com/user-attachments/assets/2ea837c2-1cd4-44f4-8f5b-05d39c60f621)


Thank you @modz2014, but problem is that I am unable to find how to create the plugins for 7Zip, there is no tutorial/skeleton to go by to create the plugins, like the entry point etc. Do you have some literature that I can have a look on how to get the plugin created? I would like to create some if I get some documenation on it. Hope your open source plugins when created can provide me with the necessary information.

**Comment by modz2014** [comment]
i have something on my blog post that might help you it harder then i thought it would because like you said nothing is out there https://modz2014.github.io/ @debugginglife if you need help or suggestion i can help dm m eon discord its my GitHub profile

**Comment by debugginglife** [comment]
Yes @modz2014 I could find nothing on the web, even your blog did not show up for some reason... I will check your blog and see if I can create some of the plugins that I require... I hope your source code comes out soon as well :-)
I will dm you if I get stuck up with something

**Comment by modz2014** [comment]
@debugginglife All good! It’s strange that the source code for my plugin isn’t available yet. No worries, though—I'm still learning as well. My next project is Inno Setup. I received a report from Hex-Rays last year indicating that I can’t include an extract password to protect the Inno Setup installer. I had been considering it before I realized I needed my Keygen for IDA Pro.

**Comment by modz2014** [comment]
@debugginglife here is the source code for pyinstaller archive its in beta atm  https://github.com/modz2014/7zip-plugin/

**Comment by modz2014** [comment]
@debugginglife did you find it interesting and did you create one yourself
