### ISSUE TITLE
CreatePackageFromFiles seems to fire callback prior to finishing packaging

### ISSUE THREAD

**Issue by JosephCoppola** [electron/asar#114]
Asar Version: 0.12.3

Hello. When calling CreatePackageFromFiles we pass a callback to determine when the packaging has finished. Oddly enough, when the callback is fired it seems that Asar is still doing something with the .asar archive. Our build pipeline tries to package up everything with NSIS after packaging with Asar, but when it gets to packaging our .asar archive it is unable to open it. If I set a time out for 3 to 5 seconds before we try to run our installer script it will be able to access the .asar file correctly. I'd rather not use setTimeout to solve this issue, and was hoping for some insight on this issue. Are we using the function incorrectly? Thank you.

Note: I did upgrade to the latest build, 0.13.0 and saw the same behavior.

**Comment by MarshallOfSound** [comment]
Closing this old issue as it is likely fixed by now, if not please raise a new issue.
