### ISSUE TITLE
[Question/bug] Modules access problem

### ISSUE THREAD

**Issue by cumajkeee** [electron/asar#115]
Guys, looking for your help here:
I've suddenly have a reports form few users on Windows that they are facing following error:

ENOENT, node_modules\keytar\build\Release\keytar.node not found in C:\Users\...\AppData\Local\Programs\App\resources\app.asar

When got users app.asar and listed entries - file is in place.
Could you please suggest, what can affect this?

The problem is only with modules that are had to be rebuild into native lang.
Thanks.

**Comment by ddavidebor** [comment]
Similar problems here on all platforms

**Comment by rogeru** [comment]
We see the same issue with the bunyan module which is also built natively. We confirmed the module is part of the asar package. The problem only happens with a few users, and even for those not consistently.

**Comment by ddavidebor** [comment]
Our problem was that we were trying to access the file through APIs not supported by asar

**Comment by cumajkeee** [comment]
In our case it's simple require('module') and it throw error that file .node not found.

**Comment by ddavidebor** [comment]
@cumajkeee it is looking for the module in a directory with  a ".asar" somewhere in between?

**Comment by cumajkeee** [comment]
@ddavidebor yes, inside asar. Main problem that this is sporadic error, it could happen, and could not for the same user.

**Comment by ddavidebor** [comment]
I think some of our problems was because we used __dirname
https://nodejs.org/docs/latest/api/globals.html#globals_dirname and it was
looking inside ../app.asar/... instead of ../app/... (or something like
that, i'm recalling from memory)

Il giorno lun 3 apr 2017 alle ore 15:51 cumajkeee <notifications@github.com>
ha scritto:

**Comment by cumajkeee** [comment]
@kevinsawicki, does team work on the project?

**Comment by adeperio** [comment]
Can confirm I am getting this too on client deployments in Windows. Using the https://github.com/atom/node-keytar library. First we've seen it, and has only popped up once in our error reports
