### ISSUE TITLE
NPM Refuses to install asar

### ISSUE THREAD

**Issue by jeffreyroberts** [electron/asar#122]
└──╼ npm install asar
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/Cellar/node/7.10.0/bin/node" "/usr/local/bin/npm" "install" "asar"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ENOSELF

npm ERR! Refusing to install package with name "asar" under a package
npm ERR! also called "asar". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jlroberts/.npm/_logs/2017-05-22T22_35_17_439Z-debug.log

> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.10.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'asar' ]
2 info using npm@4.2.0
3 info using node@v7.10.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData asar
8 silly fetchNamedPackageData asar
9 silly mapToRegistry name asar
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'asar',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'asar',
12 silly mapToRegistry   name: 'asar',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/asar
14 verbose request uri https://registry.npmjs.org/asar
15 verbose request no auth needed
16 info attempt registry request try #1 at 6:35:17 PM
17 verbose request id 2b4d8b75f6f8ea0b
18 verbose etag W/"59235b62-c842"
19 verbose lastModified Mon, 22 May 2017 21:42:58 GMT
20 http request GET https://registry.npmjs.org/asar
21 http 304 https://registry.npmjs.org/asar
22 verbose headers { date: 'Mon, 22 May 2017 22:35:17 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   etag: 'W/"59235b62-c842"',
22 verbose headers   age: '57',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-mia1321-MIA',
22 verbose headers   'x-cache': 'HIT',
22 verbose headers   'x-cache-hits': '1',
22 verbose headers   'x-timer': 'S1495492517.400937,VS0,VE0',
22 verbose headers   vary: 'Accept-Encoding' }
23 silly get cb [ 304,
23 silly get   { date: 'Mon, 22 May 2017 22:35:17 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     'cache-control': 'max-age=300',
23 silly get     etag: 'W/"59235b62-c842"',
23 silly get     age: '57',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-mia1321-MIA',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1495492517.400937,VS0,VE0',
23 silly get     vary: 'Accept-Encoding' } ]
24 verbose etag https://registry.npmjs.org/asar from cache
25 verbose get saving asar to /Users/jlroberts/.npm/registry.npmjs.org/asar/.cache.json
26 verbose correctMkdir /Users/jlroberts/.npm correctMkdir not in flight; initializing
27 silly install normalizeTree
28 silly loadCurrentTree Finishing
29 silly loadIdealTree Starting
30 silly install loadIdealTree
31 silly cloneCurrentTree Starting
32 silly install cloneCurrentTreeToIdealTree
33 silly cloneCurrentTree Finishing
34 silly loadShrinkwrap Starting
35 silly install loadShrinkwrap
36 silly loadShrinkwrap Finishing
37 silly loadAllDepsIntoIdealTree Starting
38 silly install loadAllDepsIntoIdealTree
39 silly rollbackFailedOptional Starting
40 silly rollbackFailedOptional Finishing
41 silly runTopLevelLifecycles Finishing
42 silly install printInstalled
43 verbose stack Error: Refusing to install package with name "asar" under a package
43 verbose stack also called "asar". Did you name your project the same
43 verbose stack as the dependency you're installing?
43 verbose stack
43 verbose stack For more information, see:
43 verbose stack     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
43 verbose stack     at checkSelf (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:53:14)
43 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
43 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
43 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
43 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/validate-args.js:16:5
43 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
43 verbose stack     at Array.forEach (native)
43 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
43 verbose stack     at Array.forEach (native)
43 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
44 verbose cwd /Users/jlroberts/Downloads/asar-0.13.0/bin
45 error Darwin 16.5.0
46 error argv "/usr/local/Cellar/node/7.10.0/bin/node" "/usr/local/bin/npm" "install" "asar"
47 error node v7.10.0
48 error npm  v4.2.0
49 error code ENOSELF
50 error Refusing to install package with name "asar" under a package
50 error also called "asar". Did you name your project the same
50 error as the dependency you're installing?
50 error
50 error For more information, see:
50 error     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]

**Comment by kevinsawicki** [comment]
>  Refusing to install package with name "asar" under a package
> 50 error also called "asar". Did you name your project the same
> 50 error as the dependency you're installing?

I believe this is the issue ☝️ 

You can't have a project named the same as one of its dependencies and it looks like the project you are using `asar` in is also named `asar.
