### ISSUE TITLE
Unpack-Dir options not work in windows??

### ISSUE THREAD

**Issue by tain335** [electron/asar#124]
I have try many times, use 'asar pack node_modules node_modules.asar --unpack-dir "{electron}"' in window cmd.exe, but asar didn't ingore electron folder

**Comment by eprunier** [comment]
Same problem here, "--unpack-dir" is ignored.
asar 0.13.0 on Windows 7

**Comment by jsg2021** [comment]
macOS too. v0.14.0

**Comment by MarshallOfSound** [comment]
Closing this old issue as it is likely fixed by now, if not please raise a new issue.
