### ISSUE TITLE
Confused about the behaviour of ASAR; seems to break batch files?

### ISSUE THREAD

**Issue by FjicdeiwFeiej** [electron/asar#131]
I successfully run the following command near the end of my build.bat file:
cd resources
asar pack app app.asar

It creates the app.asar from the "app" dir fine. No problem. Except that it also... breaks the batch file so it exit prematurely? Yeah, it's very weird, but it's what happens. As soon as the "asar" command has run, it ignores the rest of my .bat script. No error or anything is displayed, and nothing indicates that this is normal/expected behaviour. Can somebody explain this?

Just to make it clear: If I uncomment the "asar" line, the batch file finishes as expected. It really is due to the "asar" line for sure.

**Comment by FjicdeiwFeiej** [comment]
Hmm. It says: 'run' is not recognized as an internal or external command,operable program or batch file.

Although I also seem to recall "run" being a keyword in Windows batch files. Not sure what's up with that either.

As for using those build tools... It may become necessary in the future, if I do cross-platform stuff, but usually, those things always just introduce even more problems for me, so I tend to make my little .bats where I know exactly what is going on. (Except when I don't, such as now!)

**Comment by MarshallOfSound** [comment]
> Hmm. It says: 'run' is not recognized as an internal or external command,operable program or batch file.

I'm pretty sure "run" is the command I use everywhere, you can always drop back to `start /wait command_here`

> those things always just introduce even more problems for me

Tools like `forge` and `packager` are used by some of the largest Electron apps so I don't think you'll have any issues with them (if you do we normally respond pretty quick to issues)

**Comment by FjicdeiwFeiej** [comment]
I don't know what's going on, but while "start /wait" is at least recognized as valid syntax (this is Windows 10, BTW), even in a minimal test.bat, the asar command causes the rest of the bath file to be ignored, and opens a new command line prompt. Anything after the line with "asar" in it seems to always be butchered, whether "start /wait" is used or not. I don't understand how this is even technically possible.

**Comment by MarshallOfSound** [comment]
>  I don't understand how this is even technically possible.

I'd start checking windows error logs, something beyond ASAR is probably causing this 👍

**Comment by FjicdeiwFeiej** [comment]
Those error logs are even messier and less useful than the average open source project's documentation, so they will be of no use.

**Comment by FjicdeiwFeiej** [comment]
How can you say that this is Windows' fault when it only happens for "asar"?

**Comment by FjicdeiwFeiej** [comment]
I figured it out: it worked when I added "call" in front of the command. Weird, but at least that's out of the way. I don't really have the energy to complain about how it breaks and so on. Too many other issues to fix for that. Thanks. Hopefully, my other issues will be seen and cleared soon.
