### ISSUE TITLE
Unable to use asar.extractAll

### ISSUE THREAD

**Issue by PedroMordeP** [electron/asar#132]
Hi,
I'm trying to use on my electron app the following code

```
var tempDir = app.getPath('userData') + "\\temp";
asar.extractAll(__dirname, tempDir);
```

The __dirname is already pointing to the app.asar file but when executing is giving the error

> Uncaught Error: ENOENT,  not found in C:\[PATH]\[AppName]\resources\app.asar
> at notFoundError (ELECTRON_ASAR.js:115:19)
> at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:183:9)
> .....

The path is correct and I tried to change the path several times to test but no luck on this.
Not sure if is possible but can anyone tell me how can I unpack the asar file in runtime?
I'm trying to use node-powershell to execute some ps1 files but I need to pack the scripts but when executing the app need them outside of the asar file .

Thank you.

**Comment by malept** [comment]
You should leave the ps1 files unpacked in the first place instead of trying to extract them inside of the Electron app.
