### ISSUE TITLE
Error when trying to read JSON file with electron-store

### ISSUE THREAD

**Issue by bampakoa** [electron/asar#137]
Hi,

I use `electron-store` in my application to read JSON files and `electron-packager` to package it as an ASAR file. After packaging and running the application, I get the following error: 

`Error: ENOENT, assets\maps.json.714842314 not found in D:\myapp\resources\app.asar`

I can validate that the asar file contains a folder **assets** with a file **maps.json** inside.
After some digging I found out that `electron-store` has been updated to the latest version of `conf` which now introduces an atomic writing feature (you can find out more about this [here](https://github.com/sindresorhus/conf/commit/7d07c5dd43ab84f3887b50355bc899d8d4528cba)).

What do you think? Is the above error related with the way that asar reads files?

[Here](https://github.com/sindresorhus/electron-store/issues/30) is the related issue that I opened in `electron-store` repository, for a reference.

**Comment by MarshallOfSound** [comment]
If I had to guess we have an issue with one of our patched `fs` methods that is used inside this function.

https://github.com/npm/write-file-atomic/blob/master/index.js#L152

**Comment by helenburns** [comment]
I too am having this issue, see [here](https://github.com/sindresorhus/electron-store/issues/31), and would really appreciate a fix as it's seriously screwing my app up on windows machines!

**Comment by bampakoa** [comment]
Problem seems to have vanished in Electron 4 🎉
