### ISSUE TITLE
File order differs each archive creation

### ISSUE THREAD

**Issue by computerquip** [electron/asar#148]
I noticed while testing a delta patch system that file ordering differs each time you package an asar archive. This means if I change one line in one file then repackage my application into an asar archive, a delta patch can still be several megabytes (or possibly the size of the whole archive) large. There's #6 that talks about this but it seems to have been closed prematurely.

**Comment by githoniel** [comment]
same to me

**Comment by malept** [comment]
There is an "ordering" option to deal with this problem, introduced in https://github.com/electron/asar/pull/52
