### ISSUE TITLE
0.14.4 has a Windows regression

### ISSUE THREAD

**Issue by malept** [electron/asar#158]
Multiple people at https://github.com/electron-userland/electron-packager/issues/892 have reported that using the `asar` 0.14.4 module on Windows causes . It has been confirmed that 0.14.3 does not have this problem. See the referenced issue for the Node backtrace.

I don't have a Windows machine available for debugging, so I don't know what the cause is, apart from it's either from #145 or #154.

**Comment by zcbenz** [comment]
This should have been fixed in 0.14.5, please let me know if it is still there.

**Comment by malept** [comment]
Thanks @zcbenz! I will update the corresponding Electron Packager bug.
