### ISSUE TITLE
Question about insertLink()

### ISSUE THREAD

**Issue by Qix-** [electron/asar#160]
Just a question:

https://github.com/electron/asar/blob/master/lib/filesystem.js#L97-L105

What is the point of `stat` here (it's not used)? Are these not like symbolic/hard links? Or are they used to link outside of/adjacent to the ASAR itself?

**Comment by zcbenz** [comment]
It looks like we did some refactoring of the code but forgot to remove the parameter, feel free to start a PR to remove it.
