### ISSUE TITLE
Unpacking ???  Not Working...

### ISSUE THREAD

**Issue by Mxdi** [electron/asar#162]
Im using an npm script with electron packager... 

**"package-win": "electron-packager . BTCPlus --asar.unpack=\"{node_modules}\" --icon=assets/icons/win/icon --out=release-builds --version-string.FileDescription=CE --version-string.ProductName=\"BTC+\""**

This is not unpacking my modules. And I have tried almost every other alternative ? Why is this not working to unpack?

**Comment by malept** [comment]
You want `--asar.unpackDir`, not `--asar.unpack`.
