### ISSUE TITLE
Write without extracting

### ISSUE THREAD

**Issue by thiagorova** [electron/asar#166]
Hi!
first of all, pretty cool package!
So... I'm building an electron-based that, among other things, manages a series of user generated files. I'd like to package and encrypt my user's files to enable a permission-based online file sharing (using services like Dropbox and Google Drive). Asar suits my needs very well (no compression and extraction-less file access). 

I was just wondering if you guys were planning (I can try looking into it if you give me the go) and adding a file-write method to asar, so that I can update a single file in the package without having to do the "extract-write-package" process each time. something like:

`asar.writeFile(src, file, data-buffer)`
thanks!

**Comment by malept** [comment]
There isn't a plan to add a method like that, as far as I'm aware. Given what I know about the format, the entire file would have to be rewritten anyway, right? Which would end up being "extract-write-package" to some extent.

**Comment by thiagorova** [comment]
hummm... not really worth implementing then. a pity, though.
