### ISSUE TITLE
Extraction stops if a file has a size of < 0

### ISSUE THREAD

**Issue by sleeyax** [electron/asar#181]
Normally a file shouldn't have a size less than 0, but when it does the extraction process just exits with:

```
$ asar extract app.asar extracted

buffer.js:250
    throw new ERR_INVALID_OPT_VALUE.RangeError('size', size);
    ^

RangeError [ERR_INVALID_OPT_VALUE]: The value "-1000" is invalid for option "size"
    at Function.alloc (buffer.js:259:3)
    at new Buffer (buffer.js:177:19)
    at Object.module.exports.readFileSync (C:\Users\Me\AppData\Roaming\npm\node_modules\asar\lib\disk.js:117:16)
    at C:\Users\Me\AppData\Roaming\npm\node_modules\asar\lib\asar.js:214:28
    at Array.map (<anonymous>)
    at Object.module.exports.extractAll (C:\Users\Me\AppData\Roaming\npm\node_modules\asar\lib\asar.js:192:20)
    at Command.<anonymous> (C:\Users\Me\AppData\Roaming\npm\node_modules\asar\bin\asar.js:60:15)
    at Command.listener (C:\Users\Me\AppData\Roaming\npm\node_modules\asar\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:203:13)
    at Command.parseArgs (C:\Users\Me\AppData\Roaming\npm\node_modules\asar\node_modules\commander\index.js:651:12)
```

I think this is unexpected behaviour and the file should be skipped instead, allowing the extraction of other files in the archive to continue.

[Here is a possible fix](https://github.com/sleeyax/asar/commit/7717db7ce2086a3dfd80f4eea757a2d26ee78f9a), but I'm not sure what your thoughts are on this, so ill wait with opening a pull request.

**Comment by malept** [comment]
I think the more important question is, what causes the file size to be negative?

**Comment by sleeyax** [comment]
> I think the more important question is, what causes the file size to be negative?

I've only seen this happen once while experimenting with an electron-based application I do not own. I think it's caused by an external modification of the `size` property in the header, while leaving the `offset` intact.

**Comment by malept** [comment]
I don't know how much we should be handling cases where there are manually edited asar files. What about invalid JSON, values of the wrong type, etc.?

**Comment by sleeyax** [comment]
Imo it should throw an exception when that happens, but it shouldn't when just the file size is negative.

**Comment by sleeyax** [comment]
Meh, on second thought this issue isn't relevant. I'll just keep it to my fork & close it.

**Comment by xssc** [comment]
hey, @sleeyax , i think you should reopen this issue, it is very important "while experimenting with an electron-based application you do not own" as you put it

**Comment by sleeyax** [comment]
> 
> 
> hey, @sleeyax , i think you should reopen this issue, it is very important "while experimenting with an electron-based application you do not own" as you put it

The asar CLI tool itself shouldn't take care of rare scenarios where .asar files were modified by 3rd parties. It works as intended when used normally, so this issue stays closed.

**Comment by andrewschreiber** [comment]
Hey fellow investigators :)

If you open up one of these "obfuscated" .asars with a compatible (!) text editor (~maybe `vim app.asar`) what you find is a header:

 ```".codesign":{"size":-1000,"offset":"0"}```

The only match for `-1000` in the entire asar file. Compared to a normal asar, this obfuscated asar also has thousands of unicode characters between the header JSON and the first actual file.

I played with stripping out the unicode, changing the codesign size, etc. but kept running into JSON parsing issues when extracting.

Might revisit more later. Looks like there is a new (secret??) codesigning framework for sourcecode protection for electron

**Comment by woshidamaomao** [comment]
Modifying your local asar in node_modules is shown below

![image](https://user-images.githubusercontent.com/21979377/225841354-28902204-5d14-45b1-a9b4-ac4c727dbf0d.png)
