### ISSUE TITLE
Attempt to write outside buffer bounds

### ISSUE THREAD

**Issue by crisan-catalin** [electron/asar#183]
**Expected Behavior**
I want to extract an asar file using `asar extract app.asar` command.

**Actual Behavior**
I get the following error:
`RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds`

**To Reproduce**
Run `asar extract app.asar` command on asar file.

Screenshots
https://i.imgur.com/zmNOSqq.png

**Comment by linxiaoru** [comment]
Same here. Has anyone solved this problem yet？

**Comment by malept** [comment]
Can someone please provide a minimal testcase for this?

**Comment by AxDSan** [comment]
Do you mind sharing your `app.asar` file?

**Comment by qianlizhe** [comment]
I have same problem,this is ``app.asar`` file :[app.asar](http://39.105.52.127/app.asar.zip),please unzip after downloading.The file from  software [CocosCrator](https://www.cocos.com/en/creator)

**Comment by AxDSan** [comment]
The error "attempted to write outside buffer bounds" means exactly that, when attempting to write to the buffer it went outside its capacity, meaning it got past the amount of elements of what it's supposed to have. In this case CocosCreator asar has been packed in such a way that it doesn't even read properly because the contents have been encrypted.

I assume they used this example:

**Comment by qianlizhe** [comment]
> The error "attempted to write outside buffer bounds" means exactly that, when attempting to write to the buffer it went outside its capacity, meaning it got past the amount of elements of what it's supposed to have. In this case `CocosCreator` ASAR has been packed in such a way that it doesn't even read properly the file because the contents have been encrypted.
> 
> The unpacking process of the ASAR files starts from the very beginning, of course... The extractor needs to read the headers first and then verify its contents, like where each file is (you can read more about ASAR file format here: [ASAR Format](https://github.com/electron/asar#format)) afterwards, it just proceeds to unpack the file given its header information.
> 
> Going back to the discussion, as per example:
> 
> > Asar’s transform option allows to specify a stream transformer that is applied when the files are packed into the asar container. However at some point you will have to decrypt your files and this is where it gets really tricky. Also, if your static password leaks you’re not winning anything.
> 
> ```
> const crypto = require('crypto')
> var password = new Buffer(‘my secret password’);
> function transform(filename) {
>  return crypto.createCipher(‘aes-256-cbc’, password);
> }
> asar.createPackageWithOptions(src, dest, { transform: transform }..)
> ```
> 
> this means they have packaged their application with a specific transformation option that may have probably encrypted the contents of the headers... since when you open the file only the header is encrypted, and not the actual file contents, or even the names, which if you ask me if quite a smart thing to do!👌

Thank you for your reply, I will try to contact the developer of CocosCreator to solve this problem.

**Comment by faizananwerali** [comment]
@AxDSan I also want to encrypt my app.asar with cypher so no one can extract it source code. 
How do use it with [Electron Packager](https://github.com/electron/electron-packager)?

**Comment by eatdreamcat** [comment]
have you solved this problem?

**Comment by malept** [comment]
Since the folks who have been experiencing this problem have not responded to the request for additional information for several months, I'm going to assume that they either found the answer in another manner or decided not to pursue this issue. If I'm incorrect, they can respond with answers to the questions posed _(namely, a minimal testcase)_, and I'll reopen.

**Comment by lewisxy** [comment]
For CocosCreator's case, they customized the ASAR format (it's quite complicated and is more than just encryption) and write their own decryption code that is baked into the Electron framework.

In short, if you have to examine the JavaScript source code inside an ASAR package (for some potential legit use? I am NOT a legal expert), you can always use the [debug feature of electron](https://www.electronjs.org/docs/tutorial/debugging-main-process).

**Comment by cybercorn88** [comment]
Hi, have you contact the cocos creator team for further information? We have the same issue when we try to port creator to linux.
