### ISSUE TITLE
Python File not found error

### ISSUE THREAD

**Issue by shafique18** [electron/asar#187]
Hi,
I used a electron-packager to package a electron js application with --asar=true option, but when Im trying to run my application it gives me error as ;

Uncaught PythonShellError: C:\Users\ASUS X510\Anaconda3\envs\Shafique\python.exe: can't open file '"Project Directory"\resources\app.asar\engine\main_cleanup.py': [Errno 2] No such file or directory

Command I used for Packaging is 
electron-packager . --overwrite --icon=F:\\shafique\\geo_icon.png --extra-resource=./engine/ 

Other details 
OS - Windows 10 home
System - 64 bit

Folder which I mentioned in extra resource is visible to outer world and anyone can see the code easily, but I want to use hide the python code too from application which is not possible after asar packaging,
Please any one available for help to complete my process so I can make application with all hidden and working code.

Thanks, waiting for valuable and working responses.

**Comment by malept** [comment]
Python doesn't understand that `main_cleanup.py` is in an ASAR archive. You'll need to either exclude it from the ASAR archive or use something like [`pyasar`](https://pypi.org/project/pyasar/) in your Python code to import your other files.

**Comment by shafique18** [comment]
HI @malept ,
please provide the way pyasar is used as I dont want to show my python code to outer world if I will exclude python files from .asar files then python files are clearly visible in resource folder.
could you please provide a way which help me to hide python code from project directory like asar hide all js files in .asar

**Comment by malept** [comment]
The asar format isn't meant to obscure source code. If you need to do that, you should look for different solutions for Python.
