### ISSUE TITLE
Browser usage

### ISSUE THREAD

**Issue by Banou26** [electron/asar#197]
I'm trying to use the asar format from a browser, being able to extract/package files would be pretty nice.

Is there anyone that managed to use this package in the browser ?
If not, is there any possibilities for this package to be browser compatible?

**Comment by malept** [comment]
This module currently relies on a lot of Node.js-specific APIs. That being said, we'd be happy to review a pull request that adds browser support, if it's possible.

**Comment by Banou26** [comment]
I'm not really sure how to proceed with this though, the current code/API is very node-centric.

Should we use the same functions that this package exposes for node, but rewrite them in a way that make sense for node and the browser, e.g:
```ts
export function extractFile(archive: string, filename: string): Buffer;
// into
export function extractFile(archive: string | ReadableStream, filename: string): Buffer | ArrayBuffer;
```

Or should we expose new functions that are more suited to the browser.

Also, should we keep the current node code and make a separate version for the browser that is exposed through the `browser` package.json field or just rework the entire library to be able to work on multiple environments ?

**Comment by malept** [comment]
The primary use case is for Node, so I think it would be better to leave the current public interface, add a `browser` version, and have a set of common code where possible.

**Comment by Banou26** [comment]
Just a little heads up about this, i'm currently quite busy so i can't work on this right now, but i do intend to implement this once i'm done with some stuff.

**Comment by Banou26** [comment]
I did some work on it and managed to get a minimalist API capable of extracting and packaging asar files from the browser. *https://github.com/Banou26/asar-browser*
(I made another repo simply to have a clean work folder, we can easily put that back into the asar repo)

I tried to use native browser APIs when I could but since i'm not well versed about buffers, I just used them whenever I understood how to.
There's a lot more places where we could use them to completely remove both the `Pickle` & https://github.com/feross/buffer dependencies.
So if you guys have some time we could try to reduce the browser library weight by removing the need for those dependencies.

There is also some stuff I was not sure about, like the `ordering` option, I don't really understand what is it used for so I just skipped that.

I haven't made any tests yet but you can try it from your browser by un-commenting these test functions (Or just read down to see the tests results): https://github.com/Banou26/asar-browser/blob/master/src/index.ts#L13

I used `Blobs` as file primitive since they take a lot of different input types and can easily be converted into `ArrayBuffer`s.

The API looks like this

```js
  createPackage({
    'New folder': {
      'foo.txt': 'foo bar baz aaaa',
      'bar.txt': 'qux quux quuux'
    },
    'foo.txt': 'foo bar baz aaaa',
    'bar.txt': 'qux quux quuux'
  }) // Promise {<fulfilled>: Uint8Array(256)}
```
any Blob input type can be passed as file value, not just string

```js
const base64Pkg = `\
BAAAALwAAAC4AAAAswAAAHsiZmlsZXMiOnsiYmFyLnR4dCI6eyJzaXplIjoxNCw\
ib2Zmc2V0IjoiMCJ9LCJmb28udHh0Ijp7InNpemUiOjE2LCJvZmZzZXQiOiIxNC\
J9LCJOZXcgZm9sZGVyIjp7ImZpbGVzIjp7ImJhci50eHQiOnsic2l6ZSI6MTQsI\
m9mZnNldCI6IjMwIn0sImZvby50eHQiOnsic2l6ZSI6MTYsIm9mZnNldCI6IjQ0\
In19fX19AHF1eCBxdXV4IHF1dXV4Zm9vIGJhciBiYXogYWFhYXF1eCBxdXV4IHF\
1dXV4Zm9vIGJhciBiYXogYWFhYQ==`
const packedPkg = new Blob([Buffer.from(base64Pkg, 'base64')])

extractFile(packedPkg, '/New folder/foo.txt')
  .then(v => console.log(v.toString())) // foo bar baz aaaa

listPackage(packedPkg).then(v => console.log(v))
// (5) ["/bar.txt", "/foo.txt", "/New folder", "/New folder/bar.txt", "/New folder/foo.txt"]

extractAll(packedPkg).then(v =>
  console.log(
    Object.fromEntries(
      Object
      .entries(v)
      .map(([key, val]) => [
        key, val.toString()
      ])
    )
  )
)
/*
{
  "/bar.txt": "qux quux quuux",
  "/foo.txt": "foo bar baz aaaa",
  "/New folder": "\u0004\u0000\u0000\u0000�\u0000\u0000\u0000�\u0000\u0000\u0000�\u0000\u0000\u0000{\"files\":{\"bar.txt\":{\"size\":14,\"offset\":\"0\"},\"foo.txt\":{\"size\":16,\"offset\":\"14\"},\"New folder\":{\"files\":{\"bar.txt\":{\"size\":14,\"offset\":\"30\"},\"foo.txt\":{\"size\":16,\"offset\":\"44\"}}}}}\u0000qux quux quuuxfoo bar baz aaaaqux quux quuuxfoo bar baz aaaa",
  "/New folder/bar.txt": "qux quux quuux",
  "/New folder/foo.txt": "foo bar baz aaaa"
}
*/
```

Is this the kind of API you'd be okay with for the browser version ?

**Comment by Banou26** [comment]
I updated to the code to have an API with a `flat` option, to either pass/get a tree or a flat representation of the folders/files
*https://github.com/Banou26/asar-browser/blob/master/src/index.ts#L13*

**Comment by toyobayashi** [comment]
@Banou26 I did this, but it only support read files in asar, and run the code included in asar like nodejs project.
[https://github.com/toyobayashi/browser-asar](https://github.com/toyobayashi/browser-asar)

**Comment by Banou26** [comment]
Thanks, but I ended up writing my own (read and write) asar package to fit my needs.
https://github.com/Banou26/asar
I guess i'll close this down as there's browser alternatives now.
