### ISSUE TITLE
Check if buffer is asar file

### ISSUE THREAD

**Issue by Richienb** [electron/asar#198]
Is there a way to check if a buffer is an asar file?

**Comment by malept** [comment]
Probably by checking that the header of the buffer looks like the [asar file format](https://github.com/electron/asar#format).

**Comment by Richienb** [comment]
@malept 

> **Probably** by checking that the header of the buffer looks like the asar file format.

Can you provide a simple example?

**Comment by malept** [comment]
Unfortunately, I don't have time to do this. I would look at the asar file format that was linked earlier and adapt that to the [content sniffing](https://en.wikipedia.org/wiki/Content_sniffing) practice.
