### ISSUE TITLE
Support file exclusion/inclusion

### ISSUE THREAD

**Issue by natevw** [electron/asar#2]
When I run `asar pack . app.asar` the result is 75MB! It must be including `node_modules/atom-package-manager` and when I `asar list app.asar` it looks like it's even bundled up `.git` — so much for using this to "protect your app's resources and source code from the users" like ill-advisedly [claimed](https://github.com/atom/atom-shell/blob/master/docs/tutorial/application-packaging.md)!

Can an option be provided to exclude directories, or manually list files to bundle?

**Comment by armaseg** [comment]
Looking forward to see this working

**Comment by bengotow** [comment]
Hey folks - file inclusion / exclusion should be possible via the `--unpack-dir` option, which allows you to exclude some resources from being packaged.

https://github.com/electron/asar#excluding-multiple-resources-from-being-packed

**Comment by Slapbox** [comment]
@bengotow Is there any way to exclude files from packing programatically?

**Comment by idleberg** [comment]
@Slapbox
https://github.com/electron/asar/blob/2ec15c1c4537842bdd488a5006bfdee13808fafc/bin/asar.js#L18
