### ISSUE TITLE
Module build fail with webpack

### ISSUE THREAD

**Issue by eraychumak** [electron/asar#200]
Using `asar` in electron with webpack causes a module build fail

![image](https://user-images.githubusercontent.com/44278658/88468474-4c82f800-cedc-11ea-8825-abf985255d7b.png)

**Comment by eraychumak** [comment]
After lookin' through the src code, this fixes it:  #201

**Comment by malept** [comment]
See https://github.com/electron/asar/pull/201#issuecomment-663926658
