### ISSUE TITLE
Unable to extract asar file.

### ISSUE THREAD

**Issue by HonorMaster** [electron/asar#202]
When I try to extract an asar file, it gives me this error. 

`undefined:1
3f5P9- fr=7&*#[#i(@W=4]B#j
 ^

SyntaxError: Unexpected token f in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.module.exports.readArchiveHeaderSync `

**Comment by malept** [comment]
You're either trying to read an invalid asar file or it was [transformed](https://github.com/electron/asar/blob/v3.0.3/README.md#transform) during creation.
