### ISSUE TITLE
file links out of the package

### ISSUE THREAD

**Issue by uv-w** [electron/asar#213]
![image](https://user-images.githubusercontent.com/17735161/109253099-f9827200-7829-11eb-9e8d-a46e3349cc4c.png)

USER:
`await asar.createPackageWithOptions(inputpath, asarpath, asaroption);`

RESULT:

Error: /Users/yach/jenkins_space/workspace/yach-Mac_51_Build_Test_new_153/src/11-native/node_modules/@yachfe/config: file links out of the package
11:50:39      at Filesystem.insertLink (/Users/yach/jenkins_space/workspace/yach-Mac_51_Build_Test_new_153/src/10-pkg/packages/yachfe-cli/node_modules/asar/lib/filesystem.js:98:13)
11:50:39      at handleFile (/Users/yach/jenkins_space/workspace/yach-Mac_51_Build_Test_new_153/src/10-pkg/packages/yachfe-cli/node_modules/asar/lib/asar.js:132:20)
11:50:39      at next (/Users/yach/jenkins_space/workspace/yach-Mac_51_Build_Test_new_153/src/10-pkg/packages/yachfe-cli/node_modules/asar/lib/asar.js:148:11)
11:50:39      at next (/Users/yach/jenkins_space/workspace/yach-Mac_51_Build_Test_new_153/src/10-pkg/packages/yachfe-cli/node_modules/asar/lib/asar.js:149:12)
11:50:39      at async packasarfromnative (/Users/yach/jenkins_space/workspace/yach-Mac_51_Build_Test_new_153/src/10-pkg/packages/yachfe-cli/src/yach/yach-copy.js:215:13)
11:50:39      at async copyDist (/Users/yach/jenkins_space/workspace/yach-Mac_51_Build_Test_new_153/src/10-pkg/packages/yachfe-cli/src/yach/yach-copy.js:222:5)
11:50:39  copy dist success!

**Comment by uv-w** [comment]
asar/lib/filesystem.js  -> insertLink:

link: node_modules/crc-32/bin/crc32.njs
13:21:59  link: node_modules/image-size/bin/image-size.js
13:21:59  link: node_modules/is-docker/cli.js
13:21:59  link: node_modules/printj/bin/printj.njs
13:21:59  link: node_modules/rimraf/bin.js
13:21:59  link: node_modules/semver/bin/semver.js
13:21:59  link: node_modules/sshpk/bin/sshpk-conv
13:21:59  link: node_modules/sshpk/bin/sshpk-sign
13:21:59  link: node_modules/sshpk/bin/sshpk-verify
13:21:59  link: node_modules/uuid/bin/uuid
13:21:59  link: ../10-pkg/packages/yachfe-config
13:21:59  link: node_modules/make-dir/node_modules/semver/bin/semver.js
13:21:59  link: node_modules/qiao.util.encode/node_modules/uuid/dist/bin/uuid

**Comment by malept** [comment]
I think this is by design. Symlinks in asars can't reference files also not in the asar.
