### ISSUE TITLE
asar can not colorize the output content in Windows CMD after v3.0.0

### ISSUE THREAD

**Issue by machinewu** [electron/asar#219]
OS: Win10 x64 1809
node version: v12.18.3
asar version: v3.0.3 (problem exists after v3.0.0)

In Windows CMD, asar can not colorize the output content after v3.0.0.

The test found that there is no problem with v2.1.0.
But both 3.0.0 and 3.0.3 can not display the color code normally in Windows CMD. 

![github](https://user-images.githubusercontent.com/4166753/120782419-9016ab80-c55c-11eb-939d-2eb74c8b3469.jpg)

**Comment by MarshallOfSound** [comment]
Closing this old issue as it is likely fixed by now, if not please raise a new issue.
