### ISSUE TITLE
module cannot be found on a virtual machine,real machine don't have the problem

### ISSUE THREAD

**Issue by Confucius-Pei** [electron/asar#232]
virtual machine:
http://d.w10a.com/win7/cn_windows_7_ultimate_with_sp1_x64_dvd_677408.iso

problem:
![VirtualBox_MSEdge - Win10_04_03_2022_10_22_06](https://user-images.githubusercontent.com/5771318/156687777-f24be51d-0616-437a-affe-46e3eda782a7.png)

**Comment by MarshallOfSound** [comment]
Closing this old issue as it is likely fixed by now, if not please raise a new issue.
