### ISSUE TITLE
Folders named constructor not being packed properly

### ISSUE THREAD

**Issue by Claytonn** [electron/asar#235]
If a library includes a `/constructor` folder the folder is not packed into the asar. 

See:  https://github.com/trufflesuite/truffle/tree/master/packages/hdwallet-provider/src/constructor

**Comment by erickzhao** [comment]
Hi @Claytonn, is the repro here to run `npx asar pack` on the `hdwallet-provider` folder?

**Comment by StrangeBytesDev** [comment]
This issue appears to be back. I'm using @sinclair/typebox in an Electron app and it's constructor folder is not being included in the asar.
