### ISSUE TITLE
Extraction failed I asar: command error ?

### ISSUE THREAD

**Issue by demonkid13579** [electron/asar#240]
F:\Program Files (x86)\Steam\steamapps\common\cyberpunkdreams\resources>npx asar app.asar F:\Program Files (x86)\Steam\steamapps\common\cyberpunkdreams\resources
asar: 'Command {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  commands: [],
  options: [],
  parent: [Command],
  _allowUnknownOption: false,
  _args: [],
  rawArgs: null,
  _scriptPath: null,
  _name: '*',
  _optionValues: {},
  _storeOptionsAsProperties: true,
  _passCommandToAction: true,
  _actionResults: [],
  _actionHandler: [Function: listener],
  _executableHandler: false,
  _executableFile: null,
  _defaultCommandName: null,
  _exitCallback: null,
  _aliases: [],
  _hidden: false,
  _helpFlags: '-h, --help',
  _helpDescription: 'display help for command',
  _helpShortFlag: '-h',
  _helpLongFlag: '--help',
  _hasImplicitHelpCommand: 0,
  _helpCommandName: 'help',
  _helpCommandnameAndArgs: 'help [command]',
  _helpCommandDescription: 'display help for command',
  args: [Array],
  [Symbol(kCapture)]: false
}' is not an asar command. See 'asar --help'.

**Comment by malept** [comment]
Read `asar --help` to see how to use the `asar` CLI tool.

If you need more assistance, please use one of the [community forums](https://electronjs.org/community), including the [Electron Discord server](https://discord.gg/electronjs).
