### ISSUE TITLE
ASAR file format

### ISSUE THREAD

**Issue by phodina** [electron/asar#243]
Hi,

I'm interested in the structure of the `asar` compressed file. Is there a wiki or some documentation explaining this?

e.g. here's one for [tar](https://jackrabbit.apache.org/oak/docs/nodestore/segment/tar.html)

I've looked into one file and there was some header on the first line. 

The begining were probably some magic bytes which I removed till `{`' and then there was some function at the end which I also removed. Then I got valid JSON file.

```
$ cat /tmp/asar-stripped.json | jq | head -n 20
{
  "files": {
    "dist": {
      "files": {
        "crashReporter.js": {
          "size": 4271,
          "offset": "0",
          "integrity": {
            "algorithm": "SHA256",
            "hash": "b87a1f2d04add1bbbe001287c3e97b06b62fdc127265ad78d56f2de50ffbfc5d",
            "blockSize": 4194304,
            "blocks": [
              "b87a1f2d04add1bbbe001287c3e97b06b62fdc127265ad78d56f2de50ffbfc5d"
            ]
          }
        },
        "downloadFile.js": {
          "size": 2626,
          "offset": "4271",
          "integrity": {
Error: writing output failed: Broken pipe
pethod@CZPRGL-B18SYD3 ~/nonguix/nongnu/packages [env]$
```

**Comment by dsanders11** [comment]
Hi @phodina. The format for ASAR is described in the README file: https://github.com/electron/asar#format
