### ISSUE TITLE
goto #_undefined_# 2>NUL

### ISSUE THREAD

**Issue by raccoon666666** [electron/asar#265]
I found `endLocal & goto #_undefined_# 2>NUL || title %COMSPEC%` in asar.cmd in the node package.
What does it do?
This label is obviously invalid, 
Why not change to `endLocal & title %COMSPEC%` directly

**Comment by raccoon666666** [comment]
Thank you very much for your help.
This is the first time I have heard the concept of tunneling, and its implementation is very cool.
There is a section of code in `asar.cmd` that looks like this
```bash
call :func
goto :eof
:func
setlocal
set ret=1234
endlocal & goto #_undefined_# 2>nul || title %ret%
```
For `goto #_undefined_# 2>nul`, 
It seems to have intentionally made an error and then executed the statement after `||`
But according to tunneling, the last line is changed to
`endlocal & title% ret%`
Can also successfully obtain `%ret%`
So is `goto #_undefined_# 2>nul` completely redundant?

**Comment by phinney** [comment]
That's right, the intentional error is done so that the code after the || is guaranteed to execute and that's of course where the local environment variable %ret% is used.  When you see that technique used for the first time, it's certainly not obvious what's going on and it's certainly not explained in any online help documentation.  By the way, nice question to ask since I think it'll be helpful to others who stumble here.

**Comment by phinney** [comment]
Here's another link: https://ss64.com/nt/endlocal.html.  It discusses the endlocal&set construct.  It says that endlocal does not set or clear the errorlevel.  Reading that, it sounds like "endlocal & title %ret%' would work without the "goto #_undefined_# 2>nul" line.  The fact the endlocal does not set or clear the errorlevel adds a certain level of confusion as to how "endlocal&<any> is implemented by the shell.  By adding the redundant "goto" statement, it certainly removes some of that ambiguity.  I'm not sure but this might be a way to quarentee that the code works in different shells (i.e. cmd, powershell and windows powershell, bash.)  This is what I just hate about writing batch scripts, the code just isn't clear!

**Comment by malept** [comment]
FWIW the CMD file is provided by Node.js when you install `asar`, so the maintainers of this repo have no context as to its construction.

**Comment by raccoon666666** [comment]
This seems to be fixing the `errorlevel` to 1, possibly related to error handling
