### ISSUE TITLE
What does 'Asar' stand for?

### ISSUE THREAD

**Issue by mablinov** [electron/asar#269]
Stupid question but my curiosity is killing me! It says it "works like tar", where tar is for "Tape Archive" - does "Asar" have a similar meaning?

**Comment by castdrian** [comment]
try reading the readme, lol

**Comment by erickzhao** [comment]
I don't think the README mentions it? 🤔 

We do have it _somewhere_ in the Electron docs, though. See https://www.electronjs.org/docs/latest/glossary#asar

> ASAR stands for Atom Shell Archive Format. An [asar](https://github.com/electron/asar) archive is a simple tar-like format that concatenates files into a single file. Electron can read arbitrary files from it without unpacking the whole file.
