### ISSUE TITLE
Recursive rmdir returns error while trying to remove folder, that contains asar file.

### ISSUE THREAD

**Issue by tangjfn** [electron/asar#297]
electron version 28.1.3
v27.2.2 is OK

// const fs = require("original-fs"); // same error thrown
await fs.promises.rm("path contains asar file",{force: true, recursive: true})
// throw a error ENOTEMPTY: directory not empty, rmdir '...'
[test.zip](https://github.com/electron/asar/files/13904389/test.zip)
extract test.zip to a dir
cd the dir
electron .
input a dir contains any asar file
click rm button

**Comment by erikian** [comment]
Thanks for the issue report! This is probably an issue on Electron's side, and it's not related to the `@electron/asar` package. I've opened a new issue in Electron (https://github.com/electron/electron/issues/41008) using the test case you've provided so we can investigate it further, you can follow that issue for any new developments.
