### ISSUE TITLE
Command line utility lacks `update` command

### ISSUE THREAD

**Issue by navid-zamani** [electron/asar#317]
Right now, when I want to patch a single file in an archive, I have to unpack the entire archive, patch the file, and then pack it again. This takes an unreasonable amount of time.

Most tools have an `update` command, to allows one to save all but the necessary work. E.g. `ar` already has this, as do `tar` (with compression too) and `zip`.

It would be nice, if `asar` had this too, _if it is easy to implement and not a lot of work_, and if it doesn’t extract the archive internally anyway and saves time/resources.  

Here’s my use case, which changes the key mapping in Signal Desktop’s asar file:
```bash
npx asar extract "$asar" "$tmp"
sed -ri 's/key:( *)13,/key:\113,\1ctrlKey:\1true,/g' \
    "$tmp/ts/components/CompositionInput.js" \
    "$tmp/preload.bundle.js"
sed -ri 's/\*in//g' \
    "$tmp/_locales/de/messages.json"
npx asar pack "$tmp" "$geheilt"
rm -rf "$tmp"
```

**Comment by MarshallOfSound** [comment]
This is not an intended / supported usecase of the `asar` command, we're a file format used by developers not by end users who wish to modify other ASARs. As you note it's currently possible, but we probably won't invest any resources in making it easier via an `update` command or the like.

**Comment by L1lith** [comment]
Hello @navid-zamani, I have created a package to do exactly this. I hope it is useful to you or others who come across this issue.

[https://www.npmjs.com/package/patch-asar](https://www.npmjs.com/package/patch-asar)
