### ISSUE TITLE
TS compilation issues with version 3.2.11 compared to 3.2.10.

### ISSUE THREAD

**Issue by bmk-m** [electron/asar#324]
Error: 
`node_modules/@types/glob/index.d.ts(29,42): error TS2694: Namespace '"node_modules/minimatch/dist/commonjs/index"' has no exported member 'IOptions'.
node_modules/@types/glob/index.d.ts(74,30): error TS2724: '"node_modules/minimatch/dist/commonjs/index"' has no exported member named 'IMinimatch'. Did you mean 'Minimatch'?
node_modules/minimatch/dist/commonjs/ast.d.ts(4,5): error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.`

Seems to be caused by the newest changes adding back  @types/gob back to package.json in this commit: https://github.com/electron/asar/commit/88b5ea49c374fc9bee15be33e7135a09bc780a14#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

It was previously removed in this commit for this particular issue: https://github.com/electron/asar/commit/df7991cc9d85a34734402d360df4b0f6521be524

@types/glob is unmaintained and really should be a devDep and not an actual dependency. This is the ticket in the past that spurred the commit right above: https://github.com/electron/asar/issues/266

**Comment by emeryao** [comment]
+1

same here

**Comment by emeryao** [comment]
install the package of `@electron/asar@^3.2.13` explicitly in `package.json` seems fix this issue for my project

**Comment by erickzhao** [comment]
Hi, we had a few kinks with the build pipeline after the full TypeScript rewrite. Please upgrade to 3.2.13 at your earliest convenience!
