### ISSUE TITLE
Please remove dependency on `@types/glob` which is not required and causes breakage in typedoc builds

### ISSUE THREAD

**Issue by aaclayton** [electron/asar#330]
The version of `@types/glob` that is used by this package is incompatible with newer versions of glob or minimatch. Those libraries are written directly in typescript (this wasn't the case before) so no types package is necessary. Please remove `@types/glob` as a dependency.

Some additional context where this has come up: https://github.com/isaacs/rimraf/issues/264

**Comment by aaclayton** [comment]
It seems there is some history here. The types were removed from `dependencies` in <https://github.com/electron/asar/pull/268> which was reviewed and merged, and then at some point it moved *back* into dependencies in current https://github.com/electron/asar/blob/main/package.json.

Some intentional effort went into getting this types out of dependencies. Can this please be revisited? FYI @isaacs who did the work in #268. Do you know how this ended back up in deps?

**Comment by aaclayton** [comment]
The regression happened in https://github.com/electron/asar/pull/320

**Comment by isaacs** [comment]
No idea. I'm not involved with electron/asar, I just sent that PR because someone was complaining that glob exported the "wrong" types (for its own code, which is written in ts! lol)
