### ISSUE TITLE
`isUnpackedDir` unintentionally unpacks other directories with same dir name prefix

### ISSUE THREAD

**Issue by mmaietta** [electron/asar#331]
Hello all

I'm working on migrating electron-builder to leverage electron/asar instead of its in-house solution. In one of our unit tests I have the following structure:
```
/project# tree "/tmp/et-db411cd21f3bbd882f3a5a30c58db6ff/t-jp88Jv/asar-app-1"
/tmp/et-db411cd21f3bbd882f3a5a30c58db6ff/t-jp88Jv/asar-app-1
├── app
│   ├── package.json
│   │   └── readme.md
│   └── readme.md
├── index.html
├── index.js
├── node_modules
│   ├── @electron-builder
│   │   ├── test-smart-unpack
│   │   │   ├── foo.dll
│   │   │   └── package.json
│   │   └── test-smart-unpack-empty
│   │       └── package.json
```
`test-smart-unpack` is auto-detected by electron-builder to unpack due to the underlying `.dll` file, and in turn, that minimatch is passed to electron/asar to unpack that dir with the pattern below
```
pattern = "{node_modules/@electron-builder/test-smart-unpack,node_modules/edge-cs}"
```
https://github.com/electron/asar/blob/464e83436967438c74d8ac184b088fc780706b2d/src/asar.ts#L22-L31

The issue I'm running into is that `test-smart-unpack-empty` is **not** supposed to be getting unpacked as it fails the minimatch, but the `else` logic in `isUnpackedDir` is causing it to do a `startsWith` match on the folder path and then returns `true`.
![Image](https://github.com/user-attachments/assets/89bf9d4b-29d8-41a5-b3f2-7268ce9d2853)

What I think the `else` logic is attempting to do is to determine if the `dirPath` is _within_ the tree hierarchy of a previously-unpacked dir. Is that right?
https://github.com/electron/asar/blob/464e83436967438c74d8ac184b088fc780706b2d/src/asar.ts#L29
If so, I think an additional check is needed such that we check that the relative path is within the dir path hierarchy, and not just a `startsWith` check.
Maybe something like: `dirPath.startsWith(unpackDir) && !path.relative(dirPath, unpackDir).startsWith("../")`?

Wanted to post an issue here first to touch base with you all, in case I'm doing something wrong, before diving in deeper to see if I can PR something

**Comment by Akarinx** [comment]
maybe it's the same problem like https://github.com/electron/asar/issues/303,  and the same fix method

**Comment by mmaietta** [comment]
@Akarinx I gave the fix in https://github.com/electron/asar/pull/333 a test for #303 and it does not fix your issue. 
![Image](https://github.com/user-attachments/assets/b10d7bf5-aa59-41ff-80fd-c90100271e17)
I might be able to take a deeper look though when I have some time

**Comment by Akarinx** [comment]
@mmaietta 
I mean this line has the same issue
https://github.com/electron/asar/blob/b7730638891726666776c68116b51043d39424ef/src/crawlfs.ts#L51
and it maybe  can be fixed in the same method

**Comment by mmaietta** [comment]
Currently investigating around with that already but it doesn't seem to work the same way
