### ISSUE TITLE
Error while executing asar archive

### ISSUE THREAD

**Issue by JW-Vinayak** [electron/asar#34]
Hi,

I am trying to run an app with Electron using asar archive. It gives archive parsing error. 

[This](https://github.com/JW-Vinayak/calculator) is my app that I have created for debugging purpose which gives the same error. When executed directly with Electron, it works. I created an archive with `asar pack calculator app.asar`

And then put this newly created archive under `electron-v0.25.3-darwin-x64/Electron.app/Contents/Resources` and execute it. It gives following error.

```
Lion:~ vinayakmote$ /Users/vinayakmote/Downloads/electron-v0.25.3-darwin-x64/Electron.app/Contents/MacOS/Electron
[4555:0520/152250:ERROR:archive.cc(147)] Failed to parse header: Line: 1, column: 478873, Syntax error.
[4557:0520/152251:INFO:renderer_main.cc(207)] Renderer process started
```

Can you please give me some pointers on what could be going wrong here?

**Comment by Golammott** [comment]
While I am not a contributor, I had this same issue. 

Theres is a bug in the current version of asar and the header is getting created incorrectly.

To resolve I used asar version 0.4.4 instead of current version 0.6.1

**Comment by JW-Vinayak** [comment]
Thanks for this info @Golammott !

**Comment by MarshallOfSound** [comment]
Closing this old issue as it is likely fixed by now, if not please raise a new issue.
