### ISSUE TITLE
Spawn ENOENT

### ISSUE THREAD

**Issue by ingro** [electron/asar#35]
Not sure if is an issue with asar or electron,anyway I've packed my app in an asar archive and everything works fine, except when a module tries to spawn a process calling an archived executable file:

```
Uncaught Error: spawn C:\Program Files (x86)\TestApp\resources\app.asar\node_modules\pageres\node_modules\screenshot-stream\node_modules\phantom-bridge\node_modules\phantomjs\lib\phantom\phantomjs.exe ENOENT
```

I've tried to extract the archive and the file is indeed there, so where's the problem?

I'm running on Windows 7 x64 and Electron 0.26.1, using the latest asar (0.6.1).

Thanks,

**Comment by martinstarman** [comment]
I have similar problem. When I try load file which is in asar archive, get 
```
Uncaught Error: ENOENT: no such file or directory, open ...
``` 
error with absolute path to file.

**Comment by kevinsawicki** [comment]
`child_process.spawn` does not work for files inside an `.asar` file. You need to specify them as unpacked.

See http://electron.atom.io/docs/tutorial/application-packaging/#executing-binaries-inside-asar-archive for more details on how to do this, closing this out.

**Comment by ingro** [comment]
Thanks for the tip @kevinsawicki !

**Comment by aredfox** [comment]
I want to add that I have an app.asar.unpacked folder with the node-module being referenced inside there. Yet the spawn error says it's looking into app.asar and not into app.asar.unpacked.
I read the docs, should I manually redirect to app.asar.unpacked - or should electron handle this - as now this is unclear to me.

**Comment by kidsonfilms-python-rules** [comment]
@kevinsawicki That page now returns a 404 page, could you give an updated link or a summary of what it says in the link you provided?

**Comment by malept** [comment]
You need to whitelist executables, libraries and files accessed by those executables and libraries via the `unpack` and `unpackDir` options.

**Comment by mokchend** [comment]
> `child_process.spawn` does not work for files inside an `.asar` file. You need to specify them as unpacked.
> 
> See http://electron.atom.io/docs/tutorial/application-packaging/#executing-binaries-inside-asar-archive for more details on how to do this, closing this out.

The link is outdated and the page do not exist anymore.

**Comment by malept** [comment]
Use the Internet Archive to view a snapshot of that page, although I already described how to do it in my earlier comment.
