### ISSUE TITLE
When using --unpack, the directory info is not updated

### ISSUE THREAD

**Issue by Gregg8** [electron/asar#36]
I used the command `asar pack app app.asar --unpack *.dll` to exclude a single dll from my asar.

The file was extracted to the correct directory and it was removed from the asar file, however the dll still appears in a directory listing and when you try to extract all the files with `asar e app.asar tmp` it fails on that file:

```
fs.js:427
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory  'D:\dev\...
```

**Comment by MarshallOfSound** [comment]
Closing this old issue as it is likely fixed by now, if not please raise a new issue.
