### ISSUE TITLE
Using asar programmatically in electron

### ISSUE THREAD

**Issue by younes200** [electron/asar#51]
I try to use `atom/asar` as part of electron application, but electron use patched version of `fs` which make the `asar.createPackageWithOptions` fail complaining about the file destination.
Is there better solution than my patch : 

```
fs = do ->
  try
    return require('original-fs')
  catch e
    return require('fs')
  return
```

https://github.com/InteractiveObject/asar/blob/master/src/asar.coffee#L1

**Comment by SunspotsEU** [comment]
I've solved the same issue by giving my asar packages a different file extension (not .asar), then they're handled directly by the  `asar` package without being caught by electron's `fs`.
