### ISSUE TITLE
asar list error

### ISSUE THREAD

**Issue by caibirdme** [electron/asar#62]
run command `./node_modules/.bin/asar pack test-darwin-x64/test.app/Contents/Resources/app test-darwin-x64/test.app/Contents/Resources/app.asar`

and then `./node_modules/.bin/asar list test-darwin-x64/test.app/Contents/Resources/app.asar` there is error.
<img width="1119" alt="2016-04-08 4 42 09" src="https://cloud.githubusercontent.com/assets/8054803/14378708/f6f84574-fda8-11e5-82c8-400edbf673c0.png">
when I delete the app directory,I can't run the app by click that icon.

the electron version is 0.37.4 ,asar version is 0.11.0,electron-packager version is 6.0.0,node version is 5.10.0

**Comment by zcbenz** [comment]
I'm closing this since it has been filed at https://github.com/electron/asar/issues/62.
