### ISSUE TITLE
LSOpenURLsWithRole() failed with error -10810

### ISSUE THREAD

**Issue by gcstang** [electron/asar#66]
MacOSX: El Capitan 10.11.4
RAM: 16GB
asar: v0.11.0
electron: v1.0.2
node-java: 0.7.0

If I leave my application as a simple folder it works correctly but if I use asar to package it I get this error.

LSOpenURLsWithRole() failed with error -10810 for the file /Users/myself/GitRepositories/3rdparty/electron/out/D/Electron.app.

**Comment by vojtatranta** [comment]
same here

**Comment by bengotow** [comment]
What code are you running that is causing this error? When does the error appear? Is this at application launch, or later when you try to use something specific within the app bundle?

**Comment by vojtatranta** [comment]
Hi @bengotow thanks for your help.
In my case I just create a build and app does not run and this is output in terminal.

**Comment by gcstang** [comment]
In my case I'm running node-java, if I run it without packaging it works fine but if I package it then I get this error immediately upon attempting to run it.

**Comment by MarshallOfSound** [comment]
Closing this old issue as it is likely fixed by now, if not please raise a new issue.
