### ISSUE TITLE
out of space ENOSPC

### ISSUE THREAD

**Issue by manodupont** [electron/asar#69]
I did ; 

> asar pack . output.asar

. : Refering to my actual app, standard nodejs.

I just wanted to see what would come out of that. But the archive wasn't able to complete cause i had no more space on my drive. The archive at that point was about 14GB. What the hell is going on ? My app total weight about : 400K including node_modules.

**Comment by malept** [comment]
Unfortunately, there's nothing actionable here unless someone comes up with a reliable way to reproduce this.
