### ISSUE TITLE
A ".cache" folder ?

### ISSUE THREAD

**Issue by LeaklessGfy** [electron/asar#70]
Hello, 

I recently check this asar work and I'm a little bit confuse.
When I pack something everything seems to work but when I try to extract this .asar file, there's a `.cache` folder and now I'm wondering why this folder is create ? Can I delete it ?

Other interesting thing to know, when I pack something that I've just extract before and put it in my app only some changes are applied (generally in `index.js`), some changes on my `src` folder are not saved. Why ? Something with this cache folder ?

Command that I do:
- `asar extract app.asar ./sources/`
- Make some changes
- (in sources folder) `asar pack ./ ../app.asar`

Thank you :)

**Comment by bengotow** [comment]
Is there any chance you're using electron-prebuilt-compile or electron-compile in your project? That sounds like it's compilation cache. AFAIK ASAR doesn't create a `.cache` directory on it's own.
