### ISSUE TITLE
--unpack-dir seems to have different behaviors on OS X and Windows

### ISSUE THREAD

**Issue by romaincointepas** [electron/asar#77]
For example, with the following tree:

```
dir1
  file1.txt
  dir2
    file2.txt
    dir3
      file3.txt
```

`--unpack-dir "dir1"` on OS X will unpack everything:

```
dir1
  file1.txt
  dir2
    file2.txt
    dir3
      file3.txt
```

`--unpack-dir "dir1"` on Windows will only unpack root-level files:

```
dir1
  file1.txt
```

`--unpack-dir "dir1/**/*"` on Windows will unpack everything except root-level files:

```
dir1
  dir2
    file2.txt
    dir3
      file3.txt
```

`--unpack-dir "{dir1,dir1/**/*}"` on Windows will unpack everything:

```
dir1
  file1.txt
  dir2
    file2.txt
    dir3
      file3.txt
```

---

IMO, the OS X behavior seems to be the most logical one (`--unpack-dir "dir`" usually means that I want to unpack the entire directory including all its content).

**Comment by MarshallOfSound** [comment]
Closing this old issue as it is likely fixed by now, if not please raise a new issue.
