### ISSUE TITLE
Recursion in `asar. createPackageFromFiles` won't handle very large file lists

### ISSUE THREAD

**Issue by johnhaley81** [electron/asar#78]
Introducted in #73.

[asar.createPackageFromFiles](https://github.com/electron/asar/blob/master/src/asar.coffee#L42) now uses [recursion](https://github.com/electron/asar/blob/master/src/asar.coffee#L122-L128) to handle the list of files which is ok for a reasonable number of files but over in GitKraken we have an unreasonable number of files we're putting into the asar (~100k) which causes a `Maximum call stack size exceeded`.

As unreasonably large as the that number is, when using node/npm for a large project that no longer really becomes an edge case.

**Comment by mingyuan-xia** [comment]
This does not need to be a large number. I tested two folders, one with 9.5k and another with 4.7k files. Both failed. Finally, it works with 1.5k files.
I am packing an electron app with asar 0.12.0. With some bower dependencies, the number of files could easily grow to crash asar.

**Comment by develar** [comment]
@gerhardberger Please fix it ASAP. https://github.com/electron-userland/electron-builder/issues/606

**Comment by cmroanirgo** [comment]
I am here because of the exact same issue. I use cheerio and jszip in a project. Result: "Call Stack Exceeded", when using electron builder.
I agree that the recursion must go.

**Comment by gerhardberger** [comment]
@develar I submitted a PR with a fix. I tested with 104k files and it worked.

**Comment by kevinsawicki** [comment]
Closing as fixed by #80
