### ISSUE TITLE
CoffeeScript -> ES6

### ISSUE THREAD

**Issue by johnhaley81** [electron/asar#79]
Would you guys be up for moving from CoffeeScript to ES6 for this package? I can take a crack at it in the coming weeks if so.

**Comment by kevinsawicki** [comment]
@johnhaley81 yeah, sounds fine, we've done this in other repos by just compiling and checking in the generated `.js` files as an initial step. Then taking subsequent passes to migrate to ES6 syntax, let, const, etc., depending on what the minimum node version is being supported.

**Comment by bengotow** [comment]
Decaffeinate (decaffeinate-project.org/repl/) has gotten quite a bit better in recent months and turns CoffeeScript into ES6 rather than the ES5 produced by the CofffeeScript transpiler. We've been using it in N1 and I imagine it'd make quick work of this!

**Comment by YurySolovyov** [comment]
@kevinsawicki so what's the
>  minimum node version is being supported

ATM ? Latest one of electron main process?

**Comment by kevinsawicki** [comment]
> minimum node version is being supported

I'd say the lowest Node version still in LTS which at the time of writing, 0.12, https://github.com/nodejs/LTS#lts-schedule

**Comment by johnhaley81** [comment]
Could probably just target v4 and just wait to merge until 2017.

**Comment by kevinsawicki** [comment]
> Could probably just target v4 and just wait to merge until 2017.

Yup, that works too 👍
