### ISSUE TITLE
node-java java.import not working with a packaged electron app

### ISSUE THREAD

**Issue by antoinepairet** [electron/asar#88]
Cross reporting the issue reported in `node-java` https://github.com/joeferner/node-java/issues/352

With a package app using an asar archive, `java.import` does not work. 
The following line of code will throw an error:

`var DateTime = java.import('org.joda.time.DateTime');`

````
Error: Could not create class org.joda.time.DateTime
java.lang.NoClassDefFoundError: org/joda/time/DateTime
Caused by: java.lang.ClassNotFoundException: org.joda.time.DateTime
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

    at Error (native)
    at Java.java.import (...)
````

Only the packaged version of the app fails. 
Launching the unpackaged electron app will work fine.

The app was packaged with the following command:
````
electron-packager ./app --out=dist --asar.unpack='**/node_modules/java/**/*'
````

I guess the function `java.import` needs to be adapted in order to work with packaged electron apps.

Let me know if I can provide more information.

regards

**Comment by kevinsawicki** [comment]
Is the folder containing `org.joda.time.DateTime` unpacked as well?

**Comment by antoinepairet** [comment]
Thanks for answering so quickly 👍 

The folder containing `org.joda.time.DateTime` is unpacked too. 

The full build command is: `electron-packager ./app --out=dist --app-version=$npm_package_version --prune --overwrite --platform=darwin --arch=x64 --download.strictSSL=true --icon=./resources/osx/dentisphere_icon.icns --sign='Antoine PAIRET' --asar.unpack='{**/BLACK_FOLDER/**/*,**/node_modules/java/**/*}'`

![screen shot 2016-09-14 at 05 32 44](https://cloud.githubusercontent.com/assets/5238592/18499271/91658ed0-7a3d-11e6-9da4-85bed690a509.png)

Here is a more complete code fragment. (I can provide a full minimal example with full source if needed.)
````
'use strict';
const fs = require('fs');
const _ = require('lodash');
const path = require('path');
const java = require('java');


////////////////////////////////
// DEPENDENCIES
const dependecyPath = path.join(__dirname, 'lib');
const dependencies = fs.readdirSync('/Users/apairet/sources/dsElectron/app/BLACK_FOLDER/lib');

dependencies.forEach(function (dependency) {
    const depPath = path.join(dependecyPath, dependency)
    java.classpath.push(depPath);
});

java.classpath.push('/Users/apairet/sources/dsElectron/app/BLACK_FOLDER/javaClasses');
////////////////////////////////


////////////////////////////////
// Class instanciation
var DateTime = java.import('org.joda.time.DateTime');

````

**Comment by kevinsawicki** [comment]
Do the paths your are adding to the `java.classpath` array contain the `app.asar.unpacked` folder name or the `app.asar` folder name?

> Here is a more complete code fragment. (I can provide a full minimal example with full source if needed.)

This would be helpful.

**Comment by antoinepairet** [comment]
Here is a simple full source example showing `node-java` is not compatible with `asar` archive:
https://github.com/antoinepairet/electron-quick-start 

The code is very simple. It comes from the README of `java-node`:
````js
'use strict';
const java = require('java');

var list1 = java.newInstanceSync("java.util.ArrayList");
console.log(list1.sizeSync()); // 0
list1.addSync('item1');

module.exports = list1.sizeSync();
````

The master branch does not use `asar`. You can launch the app by using `npm start` while `npm run buildosx` will build the app. Everything works just fine.

I made a second branch (https://github.com/antoinepairet/electron-quick-start/pull/1 and https://github.com/antoinepairet/electron-quick-start/tree/asar_not_working) with `asar`. The renderer process crashes.

As you can see, I am not using `classpath` at all. So there might be more than one bug.

**Comment by kevinsawicki** [comment]
@antoinepairet I think the issue is that the internal classpath paths in `node-java` need to be using the `asar.unpacked` directory instead. https://github.com/joeferner/node-java/blob/126bfa821cefcb8af21e323990d9985936938a97/lib/nodeJavaBridge.js#L23-L31

I got it working with the following patch to your repo:

```diff
diff --git a/renderer.js b/renderer.js
index c2997dc..9744f4b 100644
--- a/renderer.js
+++ b/renderer.js
@@ -3,10 +3,18 @@
 // All of the Node.js APIs are available in this process.
 
 'use strict';
-const java = require('java');
+
+const path = require('path');
+
+let java
+if (path.extname(__dirname) === '.asar') {
+  java = require('../app.asar.unpacked/node_modules/java');
+} else {
+  java = require('java');
+}
 
 var list1 = java.newInstanceSync("java.util.ArrayList");
 console.log(list1.sizeSync()); // 0
 list1.addSync('item1');
 
-module.exports = list1.sizeSync();
\ No newline at end of file
+module.exports = list1.sizeSync();
```

**Comment by antoinepairet** [comment]
A.W.E.S.O.M.E!
That's the trick. Thanks a lot.

I have tested with a more complex example and I confirm it works.
=> Conclusion:

- Unpack all java-related files

- Make sure unpacked files are used 

I will make a PR on `java-node` to update the README and add a `Electron and ASAR` section

**Comment by gpinkham** [comment]
@antoinepairet  I know this is a really old issue but curious.  how did that code work for you?  building the electron app with webpack ends up including both requires (it doesn't run the if statement).    Did you use some other packer?       thanks!!
