### ISSUE TITLE
Please delete this project

### ISSUE THREAD

**Issue by chojrak11** [electron/asar#95]
Why another archive format? Just use 7z or ZIP - or tar. All of them are free, fast, robust and well tested already. And they can be compressed. IOW it has all features that you're just wasting time reimplementing here.

**Comment by bengotow** [comment]
The very first line of the readme makes this pretty clear: Asar is a simple extensive archive format, it works like tar that concatenates all files together without compression, **while having O(1) random access support.** The folks that built this project are quite experienced engineers and wouldn't create another format without a good reason. It would generally be a good idea to understand the problem space and motivations behind projects before suggesting they be deleted.
