### ISSUE TITLE
Unpacking tool

### ISSUE THREAD

**Issue by sk8rthug** [electron/asar#96]
Looks like none of the archivers is capable of opening this format. Is there some king of a tool to unpack asar archives? If there is no such a tool, would somebody make one please?

**Comment by bengotow** [comment]
If you take a (very) quick look at the README, you can install asar via `npm install asar -g`  and it comes with a command line interface that can pack and unpack the archives: https://github.com/electron/asar/#usage.

**Comment by sk8rthug** [comment]
Sorry, I did look at readme, but didn't understand what it's all about, because I'm kinda new to it,
Ok, I got it a little, and have managed to successfully create and unpack an archive. But I can't unpack another archive, which led me here.
[code]
C:\Users\user>asar e D:\X.asar D:\Z
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'D:\X.asar.unpacked\assets\icon\w
indows-notification-icon.png'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.module.exports.readFileSync (C:\Users\user\AppData\Roaming\npm\nod
e_modules\asar\lib\disk.js:122:19)
    at Object.module.exports.extractAll (C:\Users\user\AppData\Roaming\npm\node_
modules\asar\lib\asar.js:223:24)
    at Command.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\asar\
bin\asar:59:15)
    at Command.listener (C:\Users\user\AppData\Roaming\npm\node_modules\asar\nod
e_modules\commander\index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (C:\Users\user\AppData\Roaming\npm\node_modules\asar\no
de_modules\commander\index.js:615:12)
[/code]
What could be the reason?

**Comment by sk8rthug** [comment]
My mistake was trying to extract files from this archive outside of its native folder. Dunno how it works, but I have managed to unpack it :D After several evenings of experiments... 
Yet a user-friendly tool would be good.

**Comment by Crystal-RainSlide** [comment]
Then why not ask for a user-friendly tool which can pack & unpack .asar files and many others?
And it may allow one using a more global command like:
```
$ pack asar --add-ext ./folder-or-file-for-packing ./output/packed
```
and:
```
$ unpack --auto-detect packed.js output.js
```
It may just work as a command proxy.

Andthen, this issue should should be closed and go to stackoverflow.

(Have to say, if you just want a user-friendly tool for only one job,  it is wiser to make by your self~)

**Comment by sk8rthug** [comment]
Crystal-RainSlide, there is already a 7zip plugin for this archive format out there
http://www.tc4shell.com/en/7zip/asar/
Exactly

"Have to say, if you just want a user-friendly tool for only one job, it is wiser to make by your self~)"
If you are not good at something that you rarely need, it's wiser to ask someone who can do it faster and better.
